import express from "express";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { readFile } from "node:fs/promises";
import { streamToResponse, complete } from "./llm.js";
import {
  buildExplainMessages,
  buildChatMessages,
  buildSuggestMessages,
  buildMindmapMessages,
} from "./prompts.js";
import { fetchArxivPaper, recommendPapers } from "./arxiv.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const papersDir = path.join(__dirname, "papers");
const distDir = path.join(__dirname, "..", "dist");

const app = express();
app.use(express.json({ limit: "1mb" }));

app.get("/api/papers", async (req, res) => {
  try {
    const manifest = JSON.parse(
      await readFile(path.join(papersDir, "index.json"), "utf8")
    );
    res.json(manifest);
  } catch {
    res.json([]);
  }
});

app.get("/api/papers/:id", async (req, res) => {
  try {
    const safe = req.params.id.replace(/[^a-zA-Z0-9._-]/g, "");
    const paper = JSON.parse(
      await readFile(path.join(papersDir, `${safe}.json`), "utf8")
    );
    res.json(paper);
  } catch {
    res.status(404).json({ error: "Rodney couldn't find that paper on his shelf." });
  }
});

app.get("/api/recommend", async (req, res) => {
  try {
    res.json({ papers: await recommendPapers(String(req.query.interest || "")) });
  } catch (err) {
    res.status(502).json({ error: err.message });
  }
});

app.get("/api/arxiv", async (req, res) => {
  try {
    res.json(await fetchArxivPaper(String(req.query.id || "")));
  } catch (err) {
    res.status(err.status || 502).json({ error: err.message });
  }
});

// Content-specific suggested questions from the paper's title + abstract.
// The client falls back to static chips if this errors.
app.post("/api/suggest", async (req, res) => {
  try {
    const text = await complete(buildSuggestMessages(req.body || {}), {
      maxTokens: 300,
      temperature: 0.8,
    });
    const match = text.match(/\[[\s\S]*\]/);
    const questions = JSON.parse(match ? match[0] : text)
      .filter((q) => typeof q === "string" && q.trim())
      .slice(0, 4);
    if (!questions.length) throw new Error("empty suggestions");
    res.json({ questions });
  } catch (err) {
    console.error("[suggest]", err.message);
    res.status(502).json({ error: "no suggestions" });
  }
});

// Concept map for the Mind Map tab. Validated server-side so the client
// can trust the shape; the client shows a friendly notice on failure.
const mindmapCache = new Map();
app.post("/api/mindmap", async (req, res) => {
  const { title, abstract } = req.body || {};
  try {
    if (mindmapCache.has(title)) return res.json(mindmapCache.get(title));
    const text = await complete(buildMindmapMessages({ title, abstract }), {
      maxTokens: 500,
      temperature: 0.6,
    });
    const match = text.match(/\{[\s\S]*\}/);
    const map = JSON.parse(match ? match[0] : text);
    const nodes = (map.nodes || [])
      .filter(
        (n) =>
          n && typeof n.id === "string" && typeof n.label === "string" && n.label.trim()
      )
      .slice(0, 6)
      .map((n) => ({
        id: String(n.id),
        label: n.label.trim(),
        connects_to: typeof n.connects_to === "string" ? n.connects_to : "central",
      }));
    if (typeof map.central !== "string" || !map.central.trim() || nodes.length < 3) {
      throw new Error("bad mindmap shape");
    }
    const result = { central: map.central.trim(), nodes };
    mindmapCache.set(title, result);
    res.json(result);
  } catch (err) {
    console.error("[mindmap]", err.message);
    res.status(502).json({ error: "no mindmap" });
  }
});

app.post("/api/explain", (req, res) =>
  streamToResponse(res, buildExplainMessages(req.body || {}))
);
app.post("/api/chat", (req, res) =>
  streamToResponse(res, buildChatMessages(req.body || {}))
);

// Watch-mode assets: pre-generated by scripts/generate-demo-assets.mjs
app.get("/api/demo-assets", async (req, res) => {
  try {
    res.json(JSON.parse(await readFile(path.join(__dirname, "demoAssets.json"), "utf8")));
  } catch {
    res.status(404).json({ error: "No demo assets generated yet" });
  }
});
app.use("/assets", express.static(path.join(__dirname, "assets")));

app.use(express.static(distDir));

// SPA fallback — plain middleware, not app.get('*') (which throws in Express 5)
app.use((req, res) => {
  if (req.path.startsWith("/api/")) {
    return res.status(404).json({ error: "Not found" });
  }
  res.sendFile(path.join(distDir, "index.html"), (err) => {
    if (err && !res.headersSent) {
      res
        .status(200)
        .send("Rodney's server is up. Build the frontend with `npm run build`.");
    }
  });
});

const port = process.env.PORT || 3000;
app.listen(port, () => {
  console.log(`Rodney is perched and listening on :${port}`);
});
