import { useEffect, useRef, useState } from "react";
import { gsap, useGSAP } from "../lib/gsap.js";

let assetsPromise = null;
function loadAssets() {
  assetsPromise ||= fetch("/api/demo-assets").then((r) =>
    r.ok ? r.json() : Promise.reject(new Error("none"))
  );
  return assetsPromise;
}

// "Watch" tab: an auto-advancing, narrated card sequence built ONLY from
// assets pre-generated by scripts/generate-demo-assets.mjs. Nothing is
// generated live — if this paper has no cached assets, we say so instead of
// risking a hang in front of an audience.
export default function WatchMode({ paper }) {
  const rootRef = useRef(null);
  const audioRef = useRef(null);
  const [assets, setAssets] = useState(null);
  const [unavailable, setUnavailable] = useState(false);
  const [phase, setPhase] = useState("idle"); // idle | playing | ended
  const [cardIdx, setCardIdx] = useState(0);
  const [progress, setProgress] = useState(0);

  useEffect(() => {
    let alive = true;
    loadAssets()
      .then((a) => alive && setAssets(a))
      .catch(() => alive && setUnavailable(true));
    return () => {
      alive = false;
    };
  }, []);

  // Pause narration when the tab/panel unmounts
  useEffect(() => () => audioRef.current?.pause(), []);

  useGSAP(
    () => {
      if (rootRef.current?.querySelector(".watch-card")) {
        gsap.fromTo(
          ".watch-card",
          { opacity: 0, y: 10 },
          { opacity: 1, y: 0, duration: 0.5, ease: "power2.out" }
        );
      }
    },
    { scope: rootRef, dependencies: [cardIdx, phase, assets, unavailable] }
  );

  const isFeatured = assets && assets.paperId === paper.id;

  if (unavailable || (assets && !isFeatured)) {
    return (
      <div
        ref={rootRef}
        className="flex h-full flex-col items-center justify-center px-8 text-center"
      >
        <p className="text-sm leading-6 text-ink-soft">
          Watch mode is available for our featured paper
          {assets ? ` — “${assets.title}”` : ""}. Generating narrated videos for any
          paper is the post-hackathon roadmap.
        </p>
      </div>
    );
  }
  if (!assets) {
    return (
      <div ref={rootRef} className="flex h-full items-center justify-center">
        <p className="text-sm text-ink-faint">Loading…</p>
      </div>
    );
  }

  // Cards: title card + the three key-point cards. Audio time is split into
  // rough equal chunks per card (word-count-level precision isn't needed).
  const cards = [{ heading: assets.title, type: "title" }, ...assets.cards];

  function onTimeUpdate() {
    const audio = audioRef.current;
    if (!audio?.duration) return;
    setProgress(audio.currentTime / audio.duration);
    const idx = Math.min(
      cards.length - 1,
      Math.floor((audio.currentTime / audio.duration) * cards.length)
    );
    setCardIdx((cur) => (cur === idx ? cur : idx));
  }

  function play() {
    setPhase("playing");
    setCardIdx(0);
    const audio = audioRef.current;
    audio.currentTime = 0;
    audio.play().catch(() => setPhase("idle"));
  }

  const card = cards[cardIdx];

  return (
    <div ref={rootRef} className="flex h-full flex-col px-5 py-5">
      <audio
        ref={audioRef}
        src={assets.audio}
        onTimeUpdate={onTimeUpdate}
        onEnded={() => setPhase("ended")}
      />

      <div className="relative flex-1 overflow-hidden rounded-2xl border border-line bg-white">
        {phase === "idle" || phase === "ended" ? (
          <div className="watch-card flex h-full flex-col items-center justify-center gap-4 p-6 text-center">
            <img
              src={assets.image}
              alt=""
              className="max-h-44 w-auto rounded-xl shadow-lift"
            />
            <div className="font-display text-lg font-semibold leading-snug">
              {assets.title}
            </div>
            <button
              onClick={play}
              className="cursor-pointer rounded-full bg-rodney px-6 py-2.5 text-sm font-semibold text-white transition-colors hover:bg-rodney-deep"
            >
              {phase === "ended" ? "↺ Watch again" : "▶ Watch with Rodney"}
            </button>
          </div>
        ) : card.type === "title" ? (
          <div className="watch-card flex h-full flex-col items-center justify-center gap-4 p-6 text-center">
            <img
              src={assets.image}
              alt=""
              className="max-h-48 w-auto rounded-xl shadow-lift"
            />
            <div className="font-display text-xl font-semibold leading-snug">
              {assets.title}
            </div>
          </div>
        ) : (
          <div className="watch-card flex h-full flex-col items-center justify-center gap-3 bg-rodney-wash p-8 text-center">
            <div className="text-[11px] font-semibold uppercase tracking-widest text-rodney">
              {cardIdx} / {cards.length - 1}
            </div>
            <div className="font-display text-2xl font-semibold leading-tight">
              {card.heading}
            </div>
            <p className="max-w-xs text-[15px] leading-7 text-ink-soft">{card.text}</p>
          </div>
        )}

        {/* progress bar */}
        <div className="absolute inset-x-0 bottom-0 h-1 bg-line/60">
          <div
            className="h-full bg-rodney transition-[width] duration-300"
            style={{ width: `${progress * 100}%` }}
          />
        </div>
      </div>

      <p className="mt-3 text-center text-[11px] text-ink-faint">
        ✨ Image &amp; narration generated with DigitalOcean's Gradient AI Platform
      </p>
    </div>
  );
}
